### ISSUE TITLE
[Library] [Enhancement] Recently played tracks

### ISSUE THREAD

**Issue by xBenjo** [harbassan/spicetify-apps#100]
I know this is something that might not fit with the stats umbrella of the app, but my recently played tab is broken for spotify and I thought it might not be too hard to pull from recently played tracks last.fm.
If not, no worries. Love the app :)

**Comment by harbassan** [comment]
If i were to add this, it probably would be on the library app rather than the stats app, but i will look into it.

**Comment by harbassan** [comment]
yeah I was thinking about it and it just doesn't make sense tbh. (and your tab is probably fixed now anyway lol)
