### ISSUE TITLE
Error with the APi 🐛 

### ISSUE THREAD

**Issue by w0l6** [harbassan/spicetify-apps#101]
Console Output 

```
error Cannot fetch latest release info
error GitHub response: API rate limit exceeded for 255.255.255.255 (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

```
255.255.255.255 is my ip ( i don't leak my ip lol )
![image](https://github.com/harbassan/spicetify-apps/assets/141444067/3f5ad065-b688-44a7-acb9-db354ae91cca)

**Comment by harbassan** [comment]
This is a spicetify issue, make the issue on the spicetify-cli repo if it doesn't already exist.
