### ISSUE TITLE
[BOTH] Artists Cards not rendering

### ISSUE THREAD

**Issue by TecEash1** [harbassan/spicetify-apps#102]
<img width="714" alt="image" src="https://github.com/harbassan/spicetify-apps/assets/92249532/57d09dcb-58ca-4f06-86dd-f0004ae769ca">

I have the latest version of stats, library and spicetify I believe

**Comment by harbassan** [comment]
I think this was an issue that i fixed, try reinstalling the latest release files.

**Comment by TecEash1** [comment]
sorry, it seems to be fixed now! I think it was because I didn't uninstall and reinstall it via the CLI maybe? I just replaced the folders.
Also I apologise for the late reply...
