### ISSUE TITLE
 Endless loading

### ISSUE THREAD

**Issue by ITvlad11** [harbassan/spicetify-apps#103]
![image](https://github.com/harbassan/spicetify-apps/assets/64282882/ec9040c9-a2cb-4088-88dc-45fc7a35ae9c)
loading endlessly no matter how many times I reinstalled

**Comment by harbassan** [comment]
can you show me the console

**Comment by ITvlad11** [comment]
> can you show me the console

what needs to be done to show

**Comment by ADaga460** [comment]
i also have this problem

**Comment by harbassan** [comment]
Is this fixed on the latest stats version i just released?
