### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by Aiz4u** [harbassan/spicetify-apps#105]
In my statistics tab, only the Tracks and Library pages load any information, while the Artists and Genres tabs remain completely blank. Both Spicetify and this app are up to date. I also can't see any stats errors in console, unless this is one.

![Screenshot 2024-05-31 071809](https://github.com/harbassan/spicetify-apps/assets/127457560/fb5054c7-0dce-4793-834a-1c5d01431b06)
![Screenshot 2024-05-31 071857](https://github.com/harbassan/spicetify-apps/assets/127457560/f96466ad-3757-4ec9-be2a-a7bd69d0859b)
![Screenshot 2024-05-31 071906](https://github.com/harbassan/spicetify-apps/assets/127457560/365d0644-d446-441c-9d8e-31b2a982f8c0)

**Comment by harbassan** [comment]
You probably aren't up to date, judging by the massive gear icon which was fixed a while ago as well as the text telling you there's an update available. I will look into the main issue though, as someone else was also having it.

**Comment by Aiz4u** [comment]
![image](https://github.com/harbassan/spicetify-apps/assets/127457560/de1951e4-ef19-45d7-8d74-e1426eeb26dd)
isn't this the updated version?
