### ISSUE TITLE
[Library] Header buttons not clickable 

### ISSUE THREAD

**Issue by nathunomille** [harbassan/spicetify-apps#106]
Hi! I just installed the library app and there's an issue with the header.
I can't click the add collection button, the filter buttonm, the search button or the config button. Only Playlist, Albums, Artists and Shows are clickable. I'm on Spicetify 2.36.11, used the Powershell method.
![image](https://github.com/harbassan/spicetify-apps/assets/151762924/1d0898f1-6b45-4aa3-b710-a3bed4c82866)

**Comment by BadBronx99** [comment]
So is there a fix?
