### ISSUE TITLE
[Statistics] Sections not showing

### ISSUE THREAD

**Issue by TecEash1** [harbassan/spicetify-apps#110]
(Playlist Analysis)
<img width="743" alt="image" src="https://github.com/harbassan/spicetify-apps/assets/92249532/45c85eea-2dea-4b99-bcfb-d28b0a4753f4">

(Library analysis)
<img width="722" alt="image" src="https://github.com/harbassan/spicetify-apps/assets/92249532/5cbe0033-74ea-4b57-97a0-06950f0dd791">

**Comment by harbassan** [comment]
I've fixed this with the latest version so it should be fine now.
