### ISSUE TITLE
[Statistics] [Enhancement] "Past Week" filter option 

### ISSUE THREAD

**Issue by Raindrac** [harbassan/spicetify-apps#113]
I like to look at my scrobbles from the past week to look back at songs that I might want to relisten to, and having it available from the statistics app would make it a lot more convenient. The shortest timeframe of songs from the past month is too long for some of the tracks to be relevant to what I currently want to listen to.

Effectively I would be using it in a similar manner to the recent tracks section of Spotify, but with a better interface (I'm not a fan of how Spotify designed that section) and with a greater emphasis on what I've been playing the most. It'd be very useful!

**Comment by harbassan** [comment]
This is definitely something ill look into.

**Comment by harbassan** [comment]
I've just added this to the latest stats version, check it out.

**Comment by Raindrac** [comment]
Thanks! It's working well 🙂
