### ISSUE TITLE
[visualizer] it gets cut off at the top part when the music is loud

### ISSUE THREAD

**Issue by dxcvvxd** [harbassan/spicetify-apps#114]
pretty much what it says, i suggest maybe adding a limit to how far it can go or centering it so that its perfectly centered in its window
video and a screenshot:
![image](https://github.com/harbassan/spicetify-apps/assets/77129815/5c40897c-ac96-47ab-a426-145456d98c16)

https://github.com/harbassan/spicetify-apps/assets/77129815/bc7fc2b4-756b-41e9-8adf-c1f609e5c455

**Comment by harbassan** [comment]
make the issue here: https://github.com/Konsl/spicetify-ncs-visualizer
