### ISSUE TITLE
[Library] Massive button icons, totally empty page

### ISSUE THREAD

**Issue by MagentaMayhem** [harbassan/spicetify-apps#118]
![Screenshot 2024-07-14 211449](https://github.com/user-attachments/assets/8871c67a-2905-4710-b261-8dc149f78663)

**Comment by harbassan** [comment]
update, you're a few versions out

**Comment by MagentaMayhem** [comment]
> update, you're a few versions out

I did it just now, still it's the same.

**Comment by harbassan** [comment]
whats your spotify and spicetify versions?

**Comment by MagentaMayhem** [comment]
> whats your spotify and spicetify versions?

![image](https://github.com/user-attachments/assets/981e062d-aa14-4899-9006-042c2293a2be)

**Comment by harbassan** [comment]
Update spotify to the absolute newest available and see what happens. If its still broken then theres not much I can do because i'm stumped.

**Comment by MagentaMayhem** [comment]
> Update spotify to the absolute newest available and see what happens. If its still broken then theres not much I can do because i'm stumped, if everything is up to date (including the library app) then it shouldnt be happening.

Yeah it's working now, I installed a clean spicetify and tweaked everything.
