### ISSUE TITLE
[Statistics] New Update Still Not Working

### ISSUE THREAD

**Issue by BrandonKochnari** [harbassan/spicetify-apps#119]
Worked the first time I loaded it up but as soon as I added Last.fm key it stopped working. Tried resetting but nothing worked. Removed Last.fm key and restarted spotify but it gave me error message: Cannot read properties of undefined (reading 'map') for artists/tracks/genres and gave error message Cannot read properties of undefined (reading 'filter') for library. Tried uninstalling stats and reinstalling but gives same error message. Would appreciate if you could fix this issue tyvm.

**Comment by harbassan** [comment]
Could you open the devtools for me and show anything that pops up when you get the error? The command is `spicetify enable-devtools` in the shell and then you can ctrl-shift-I or right click open devtools the next time spotify opens.

**Comment by BrandonKochnari** [comment]
![Screenshot 2024-07-20 014142](https://github.com/user-attachments/assets/1316e7a9-5cb3-40a3-a3f6-e2609aa2ae15)

**Comment by harbassan** [comment]
could you show me the network screen just as you click on the stats tab, and look for any failed requests

**Comment by BrandonKochnari** [comment]
![image](https://github.com/user-attachments/assets/ebaf4636-2ccc-46e7-85e9-635db9043a84)
You taking abt this?

**Comment by harbassan** [comment]
yeah but the tab in front is covering it. If you could move that out of the way then i can see it. what version of spotify and spicetify are you using btw, i have a feeling you might be out of date

**Comment by BrandonKochnari** [comment]
![image](https://github.com/user-attachments/assets/a6af7758-6d0d-4b26-abdf-549304c66e08)
Reinstalled newest version of spotify as of June 20 and spicetify even later.

**Comment by harbassan** [comment]
and there are definitely no other errors on there? If so, the only thing i can say is update spicetify to latest, and double check your last fm account to make sure it actually has some data on it.

**Comment by BrandonKochnari** [comment]
Alright thanks for the help I tried uninstalling and reinstalling Spicetify as well as stats and it seems to work fine now.

**Comment by harbassan** [comment]
sweet
