### ISSUE TITLE
[Stats] Still seeing "New app update available!" after updating.

### ISSUE THREAD

**Issue by swaggyP36000** [harbassan/spicetify-apps#122]
I tried uninstalling and installing the latest version, and still get that message at the top

**Comment by LeXoLz** [comment]
Can confirm.

**Comment by TypicalZedF** [comment]
Same issue here

**Comment by harbassan** [comment]
My fault, ignore it for now.

**Comment by hyunicode** [comment]
temporary solution✌️
```css
#stats-app > .new-update{
  display: none;
}
```
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/12ba7707-e81a-42f9-86b8-e1929714fdfc">

**Comment by harbassan** [comment]
yeah just update to the latest version i just released and it'll go away
