### ISSUE TITLE
[Stats] Failed To Fetch Anything

### ISSUE THREAD

**Issue by toxtodo** [harbassan/spicetify-apps#128]
Nothing's working except for the library stats.
Do I need to send a screenshot of the error console logs for each one? Like, separate screenshots for artists, tracks, albums, genres, and charts?

![Screenshot_13](https://github.com/user-attachments/assets/2bcd630f-291d-4fd8-aba1-bee55e50cf57)
![Screenshot_14](https://github.com/user-attachments/assets/f52f96df-037a-4f5c-884f-a54ff78a7d2b)
![Screenshot_15](https://github.com/user-attachments/assets/9ac4dc5c-1461-4cc7-a756-5e7b4662a10a)
![Screenshot_16](https://github.com/user-attachments/assets/3396409c-be70-4b70-83b8-8688b47026e9)
![Screenshot_17](https://github.com/user-attachments/assets/e6c97620-9108-43c3-9632-a33631cf009d)

![Screenshot_18](https://github.com/user-attachments/assets/8acd619d-23e0-421e-a073-52a821b488fb)

**Comment by toxtodo** [comment]
I also want to add that this message won't go away, even though I've refreshed it and even reinstalled from scratch. The message just stays there.

This message appeared right after the latest update. I didn't open an issue about it immediately because it wasn't really bothering me, but since we're discussing it and I've opened an issue for something big, I decided to add it. Btw, after the update, statistics were working fine.

![Screenshot_20](https://github.com/user-attachments/assets/c09c854b-fb92-4305-ba89-1b214e9b3d47)

**Comment by celolopes** [comment]
This issue only occurs if the 'Use Last.fm for Stats' option is enabled. Just disable this option as shown in the image, close Spotify, and reopen it to fix the issue. At least it worked for me.

![CleanShot 2024-08-08 at 09 20 29@2x](https://github.com/user-attachments/assets/b14b2030-b085-4e4c-b09c-d5cdfe00463b)

**Comment by toxtodo** [comment]
> This issue only occurs if the 'Use Last.fm for Stats' option is enabled. Just disable this option as shown in the image, close Spotify, and reopen it to fix the issue. At least it worked for me.
> 
> ![CleanShot 2024-08-08 at 09 20 29@2x](https://private-user-images.githubusercontent.com/67067508/356219106-b14b2030-b085-4e4c-b09c-d5cdfe00463b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjkxOTEsIm5iZiI6MTcyMzEyODg5MSwicGF0aCI6Ii82NzA2NzUwOC8zNTYyMTkxMDYtYjE0YjIwMzAtYjA4NS00ZTRjLWIwOWMtZDVjZGZlMDA0NjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE0NTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZGFjNzAzZjlmMTY0NDM2NDczNTc2MjY1YmVlNmI5N2QwYTdiN2VjZjgzNmU1ZDQxOWI3NDE2ZWNiMjExMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CBFQgj4tk4hjT9xJrTbIOb4E67O4K74czyOHRGQhT3w)

Oh, thanks! I turned off using last.fm, and now everything works, except for the charts. Charts are still giving that error, probably because the chart statistics function is parsed from last.fm by default and can't be fixed by just turning off the function you told me to.

**Comment by toxtodo** [comment]
Hey guys, I'm totally lost on what happened, but today I noticed that everything's working fine with last.fm on, including the charts. But the message "New app update available! Visit harbassan/spicetify-apps to install." still hasn't gone away, even though I'm 100% sure I've got the latest version.

**Comment by harbassan** [comment]
Ignore the message, that's an issue on my part. In regards to the last.fm stuff, let me know if anything comes to mind about what you might have done specifically, but its probably an issue on their side so no need to worry. Is it a new lfm account maybe? Or did you just now enable the spotify sync?

**Comment by toxtodo** [comment]
> Ignore the message, that's an issue on my part. In regards to the last.fm stuff, let me know if anything comes to mind about what you might have done specifically, but its probably an issue on their side so no need to worry. Is it a new lfm account maybe? Or did you just now enable the spotify sync?



> Ignore the message, that's an issue on my part. In regards to the last.fm stuff, let me know if anything comes to mind about what you might have done specifically, but its probably an issue on their side so no need to worry. Is it a new lfm account maybe? Or did you just now enable the spotify sync?

This is without a doubt my primary account. I can definitively say that I haven't made any changes to the LFM account or its associated API key. As for the sync mentioned, I simply reactivated the LFM feature. I was advised to disable it to access some statistics, but now on, I decided to re-enable it
![Screenshot_22](https://github.com/user-attachments/assets/e48c3cb1-da6c-448f-8827-d7aef51cc474)

Probably there was some gnarly issue on lfm side. They're kinda excused for these mistakes, ya know? Just a teeny-tiny company with a dinky site that gets hit up by a measly 20 million folks a month, lol.

**Comment by harbassan** [comment]
Oh I see, it might have just been an issue with needing to refresh then. Ill put that in the release description so it might fix the issue for other people. thanks!
