### ISSUE TITLE
Playlist Stats shows error reading 'isoString'

### ISSUE THREAD

**Issue by goldenwario** [harbassan/spicetify-apps#129]
not being able to show the stats for my playlist
Playlist link: https://open.spotify.com/playlist/3HzyXE7mOcshiSfeCB8Spp?si=df4a5a34b2f846c6
![image](https://github.com/user-attachments/assets/4964753d-7a41-42cc-9d6f-6a4a433ebf32)

**Comment by goldenwario** [comment]
Still hasn't been fixed...

I want to add that the playlist is pretty big (1214 songs as of now) so that's probably why it's breaking

**Comment by harbassan** [comment]
> Still hasn't been fixed...

Patience please lol, I've made the actual fix but I'm waiting on a few other things until I make the next release.

> I want to add that the playlist is pretty big (1214 songs as of now) so that's probably why it's breaking

Don't worry that's not the problem, its just that a few albums don't have release dates set.

**Comment by harbassan** [comment]
fixed in latest release
