### ISSUE TITLE
[Stats] Cannot read properties of undefined (reading 'genres')

### ISSUE THREAD

**Issue by TecEash1** [harbassan/spicetify-apps#134]
This error happens on all playlist stats:
<img width="763" alt="image" src="https://github.com/user-attachments/assets/7e13fe65-c962-41f6-b84e-5d462208815b">

**Comment by harbassan** [comment]
can you give me the link to one of your playlists?

**Comment by TecEash1** [comment]
The error happens on all playlists not just mine. Including spotifys official playlists. error:

```console
stats - audioFeatures fetch time: 112.79999999993015
extension.js:6095 stats - artistMetas fetch time: 496.39999999990687
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Black.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Book.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

Image:
<img width="525" alt="image" src="https://github.com/user-attachments/assets/061888db-fe7b-46b3-b2e5-604a010a4336">


Also just a note after clicking trying multiple times it seems to load correctly.
errors also include ``undefined (reading 'date')`` 2nd attempt
3rd attempt it works fine, if I reload select a different playlist the same things happen in that order, if I select the same playlist as I did before it works perfectly, maybe because its cached?

**Comment by TecEash1** [comment]
This seems to be resolved for me now! :)
