### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by apollo-kun** [harbassan/spicetify-apps#152]
hello, i'm kinda new to this and I need help. I've been encountering this problem over and over again, is there something that I missed?
I can't find the index.js file, it's apparently missing. any way to fix this?

![image_2024-10-17_043358405](https://github.com/user-attachments/assets/585312ca-af4c-42d3-a392-f386cdc80956)

**Comment by cyjico** [comment]
https://github.com/harbassan/spicetify-apps/issues/73
