### ISSUE TITLE
[Stats] Top Tracks cannot be played as a playlist

### ISSUE THREAD

**Issue by muniss950** [harbassan/spicetify-apps#172]
The top tracks in the stats can only be played separately. It would be much better if it is saved as a playlist.
![image](https://github.com/user-attachments/assets/214f59b9-0f7d-43cd-92ab-096dba3a3a85)

**Comment by MrBiscuit921** [comment]
![image](https://github.com/user-attachments/assets/402cdb9b-f7ce-4516-98ff-f96b67e38a5b)
its there for me

**Comment by muniss950** [comment]
funny cus i was actually using your repo. Also are you getting chart?,i am getting lastfm api error

**Comment by MrBiscuit921** [comment]
yeah im getting that error, if only the settings button worked we would be able to add the api key

**Comment by muniss950** [comment]
ok so for some reason the PageContainer does not seem to be call props.

**Comment by muniss950** [comment]
so i just added the play button in the code outside.
Its not exactly fixed but its working for me.
![image](https://github.com/user-attachments/assets/c20de068-3db9-4306-a966-98485f3c3306)
