### ISSUE TITLE
[Feature Request] Local files support

### ISSUE THREAD

**Issue by chocolatederp** [harbassan/spicetify-apps#29]
id love if you add local file support, i understand that local files dont work with **all** of the features, but id love to have them in things like my top tracks, and maybe the ability to remove certain playlists from being counted in the statistics if possible

Thanks :3

**Comment by harbassan** [comment]
I'll definitely look into this, for some of the stats ive just been filtering them out because it causes errors when they've essentially got no info whatsoever. For someone who organises their local files tho I could try and get this to work.
