### ISSUE TITLE
[Statistics] playlist stats not showing

### ISSUE THREAD

**Issue by bluueray** [harbassan/spicetify-apps#62]
when i click on the lil "playlist-stats" icon next to the arrows it open this
![image](https://github.com/harbassan/spicetify-apps/assets/100145145/76723f14-ccf7-44a7-b8da-435e53f2e44c)
then load like normal i presume then when it's finished loading just show nothing at all
here is the console screenshot
![image](https://github.com/harbassan/spicetify-apps/assets/100145145/48d64996-cf2e-434e-9344-02caf73f7ff7)

**Comment by harbassan** [comment]
make sure spicetify is at the latest version, seems like thats the cause of the issue.

**Comment by zeroma25** [comment]
same problem, Spotify v1.2.30.1135.g02fef27a, Spicetify v2.31.0

**Comment by N72826** [comment]
same problem, Spotify 1.2.30.1135.g02fef27a, Spicetify v2.31.2

The rest of the stats work in the "Statistics" tab but the playlist stats returns a blank page.

**Comment by Shakierguide707** [comment]
I have the same problem Spotify 1.2.33.1039.g8ddb5918    Spicetify v2.34.1

**Comment by kushagra-xo** [comment]
i can reproduce aswell

**Comment by harbassan** [comment]
fixed in latest release, stat-v0.3.2
