### ISSUE TITLE
Literally no page works

### ISSUE THREAD

**Issue by oXglol** [harbassan/spicetify-apps#64]
![image](https://github.com/harbassan/spicetify-apps/assets/76590431/5dca5a11-8c7a-46e5-8ca7-84b36b1a6044)
![image](https://github.com/harbassan/spicetify-apps/assets/76590431/1554dbdf-92e0-4c68-a387-4a2f692b3f8e)
![image](https://github.com/harbassan/spicetify-apps/assets/76590431/90e8f19d-eae9-407b-9988-235cd3d103e5)
![image](https://github.com/harbassan/spicetify-apps/assets/76590431/41f31cc0-6377-4dce-a933-e46df797c60b)
![image](https://github.com/harbassan/spicetify-apps/assets/76590431/6e7fa50c-e474-4d5c-86a6-6cff0da736c2)
Just Installed it via the download link in the readme, made a last.fm account and pasted in my api key. Also on the Albums page it says "Failed to Fetch Top Artists"
Spicetify v2.31.2

**Comment by UP5S** [comment]
> ![image](https://private-user-images.githubusercontent.com/76590431/304430148-5dca5a11-8c7a-46e5-8ca7-84b36b1a6044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTE0ODQsIm5iZiI6MTcwNzg1MTE4NCwicGF0aCI6Ii83NjU5MDQzMS8zMDQ0MzAxNDgtNWRjYTVhMTEtOGM3YS00NmU1LThjYTctODRiMzZiMWE2MDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNmUzMTFkM2JkZGZhNjY3NGI3MWJhZDYxM2U5YjVlZDBkYWQ2ZWQ2MzkyODQxNGVmZmZjOTQxMmMwYjg2ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezguDGmDvw8UrNgVjvvF-s_WR1sNW6zuS_MGeHRkVgQ) ![image](https://private-user-images.githubusercontent.com/76590431/304430245-1554dbdf-92e0-4c68-a387-4a2f692b3f8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTE0ODQsIm5iZiI6MTcwNzg1MTE4NCwicGF0aCI6Ii83NjU5MDQzMS8zMDQ0MzAyNDUtMTU1NGRiZGYtOTJlMC00YzY4LWEzODctNGEyZjY5MmIzZjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OTVhZjRmNTViOWM0MTUyMmZkMmIxNGUxOWIwZWZmODdlYTVkOGQ4MGQ3MWQyMmY3ZDQ4MGFlMTQ5ZmIwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W4593_e_SqYWYGxb3kZkj1DyhaRi9szoC8awqNq34WQ) ![image](https://private-user-images.githubusercontent.com/76590431/304430271-90e8f19d-eae9-407b-9988-235cd3d103e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTE0ODQsIm5iZiI6MTcwNzg1MTE4NCwicGF0aCI6Ii83NjU5MDQzMS8zMDQ0MzAyNzEtOTBlOGYxOWQtZWFlOS00MDdiLTk5ODgtMjM1Y2QzZDEwM2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMTBiNTFjZWZiZmJlNzJmMDBjNWYwZWQzNGY3MDcxOWRjMzI5MjNjNGZiMDlhM2ExNzM2ZDdiMjNhNTY3NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.chQboO_aC7CYA6cgOa-FUd_7Zejx3Jf_uxa7w3puYC8) ![image](https://private-user-images.githubusercontent.com/76590431/304430360-41f31cc0-6377-4dce-a933-e46df797c60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTE0ODQsIm5iZiI6MTcwNzg1MTE4NCwicGF0aCI6Ii83NjU5MDQzMS8zMDQ0MzAzNjAtNDFmMzFjYzAtNjM3Ny00ZGNlLWE5MzMtZTQ2ZGY3OTdjNjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjFjYjkyYTQ5YTgyMjZiNzNiM2U3ZDA3NWRhNDIwMGNmMjYxYzQxNTJkMTk5MmU5OWJjNmQ2OTMxZjQxYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_IoodwpHlyGoqOFqByMPvvdlxriCGGKfwqYQnQw4_w) ![image](https://private-user-images.githubusercontent.com/76590431/304430722-6e7fa50c-e474-4d5c-86a6-6cff0da736c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTE0ODQsIm5iZiI6MTcwNzg1MTE4NCwicGF0aCI6Ii83NjU5MDQzMS8zMDQ0MzA3MjItNmU3ZmE1MGMtZTQ3NC00ZDVjLTg2YTYtNmNmZjBkYTczNmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjM2MmUzYzgxMWRlMDFjOTViNDkxMzY1YzdkNGI2NDdmOTAyZGU0ZDY0ODkyM2YwMDFmN2IwMTNmYzkzZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i9CG8igg104rf6TjpVl6vLxkUdwGLMwGE2yx_UF_-n0) Just Installed it via the download link in the readme, made a last.fm account and pasted in my api key. Also on the Albums page it says "Failed to Fetch Top Artists" Spicetify v2.31.2

I have the same issue as well. I think it has to do with the latest version, because after updating a lot of other extensions and custom apps aren't working for me either. Is there a way to downgrade to the previous version?

**Comment by Codfish246** [comment]
Having the same issue, no page works, either using spotify or lastfm for stats. Though the GET request links to the last.fm api return an expected json response when visiting them in the browser
![msedge_CbRxjqO0M4](https://github.com/harbassan/spicetify-apps/assets/23464269/9137bbc1-9cf6-4be7-a275-4d33a59cb79d)
![msedge_GMnAlqFc3P](https://github.com/harbassan/spicetify-apps/assets/23464269/fb8d5eb4-fba7-4509-8307-eae7b25088d8)
![msedge_4X13izXZec](https://github.com/harbassan/spicetify-apps/assets/23464269/56001c77-ef25-40dc-8f44-3ae72f97511c)
![msedge_v5qGNw2pYz](https://github.com/harbassan/spicetify-apps/assets/23464269/f063721c-d536-47c7-b79e-a1f23334c820)
![msedge_Kw5u87RIcK](https://github.com/harbassan/spicetify-apps/assets/23464269/c0eb0307-e525-461f-95be-a0550a249e85)
![msedge_SDhRy1O5E1](https://github.com/harbassan/spicetify-apps/assets/23464269/e9f49c35-715e-4fc6-9ac0-0975131fc364)
![msedge_YxXN72rGJR](https://github.com/harbassan/spicetify-apps/assets/23464269/0593b38d-b019-42b5-b94e-b0e9dc541536)

**Comment by GhosttRiderrr** [comment]
Im having the exact same issue
![image](https://github.com/harbassan/spicetify-apps/assets/137924797/ef8be553-59af-4c93-92e1-8f49bdb41362)

**Comment by harbassan** [comment]
I'm aware of this, it's a spicetify issue in general:
![image](https://github.com/harbassan/spicetify-apps/assets/84175605/5b19d27e-e08f-4ce7-89cc-353c5c31eab0)
otherwise if you cant be bothered downgrading you'll just have to be patient until the fix comes.

**Comment by Codfish246** [comment]
Thanks, just letting you know all pages seem to work mostly fine now (with both spotify and lastfm as source)
![Spotify_X3ppX7xRjR](https://github.com/harbassan/spicetify-apps/assets/23464269/63fa188d-ca70-4381-bc1e-f5fcd5641d23)

**Comment by hyunicode** [comment]
> Thanks, just letting you know all pages seem to work mostly fine now (with both spotify and lastfm as source) ![Spotify_X3ppX7xRjR](https://private-user-images.githubusercontent.com/23464269/308747208-63fa188d-ca70-4381-bc1e-f5fcd5641d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjQ1NjAsIm5iZiI6MTcwOTIyNDI2MCwicGF0aCI6Ii8yMzQ2NDI2OS8zMDg3NDcyMDgtNjNmYTE4OGQtY2E3MC00MzgxLWJjMWUtZjVmY2Q1NjQxZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE2MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YTM3YTY0YjFkN2VkYTg1NmNjZWEzZTliNDc5Y2I1OTZhMzY4YzlkZDVlNjY4YWUwZjRmODhlY2ZjMWJkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ShFEDJbfN30W8RaPh9Uo4KSXGdCmWPfWwPzkWoYBCc4)

It looks like my stats are not working again，but it was fine when I just updated spicetify

**Comment by harbassan** [comment]
I can confirm that everything should be working again now on the latest spicetify version (v2.33.2). After you update you might just have to wait a minute while it refetches everything.

**Comment by hyunicode** [comment]
> I can confirm that everything should be working again now on the latest spicetify version (v2.33.2). After you update you might just have to wait a minute while it refetches everything.

🥹
![image](https://github.com/harbassan/spicetify-apps/assets/81250265/335ee165-4eb0-48ff-8cfe-6c8d5a35771d)
![image](https://github.com/harbassan/spicetify-apps/assets/81250265/ae4d6c03-07b9-42a6-88a8-42f0fd8c69ce)

**Comment by harbassan** [comment]
try manually refreshing as well to force a reload.
