### ISSUE TITLE
Every tab says Failed to Fetch

### ISSUE THREAD

**Issue by CheckisCheck** [harbassan/spicetify-apps#66]
Exactly what the title says, i've tried uninstalling and re-installing nothing changed.
![image](https://github.com/harbassan/spicetify-apps/assets/58380014/5721e760-b6ab-40e5-9099-cb920fd4d85b)
![image](https://github.com/harbassan/spicetify-apps/assets/58380014/3eae5f9b-dbc4-4962-8612-bd2bba388bc1)
![image](https://github.com/harbassan/spicetify-apps/assets/58380014/683ac964-9878-464a-bc5e-8f9a315a217b)

**Comment by Codfish246** [comment]
see https://github.com/harbassan/spicetify-apps/issues/64#issuecomment-1945108373
