### ISSUE TITLE
infinite statistics download

### ISSUE THREAD

**Issue by DBSuwu** [harbassan/spicetify-apps#67]
After installing, I can't get the stats to load, I waited for a long time but nothing 

![изображение](https://github.com/harbassan/spicetify-apps/assets/70775103/9fedd030-a948-4f6a-a7e5-58b9e9241d44)
![изображение](https://github.com/harbassan/spicetify-apps/assets/70775103/3b80541c-509c-4fef-a3a4-14763e8d4478)

**Comment by harbassan** [comment]
the api server isn't responding, so its most likely an internet related problem.

**Comment by DBSuwu** [comment]
but there's nothing wrong with the internet, like everything's loading, etc..

**Comment by rockenren** [comment]
API server responds with 403 (Forbidden), it is a block from Spotify side ("Spotify is unavailable in your country" in my case).
I have same issue, but stats working fine via proxy.
