### ISSUE TITLE
"index.js" is missing to install the app

### ISSUE THREAD

**Issue by Enymlv** [harbassan/spicetify-apps#69]
First time in my life I've used spicetify and github, so I'm no expert.

But I'm missing "index.js" to install the application properly 
Do you have a solution to help me? 

![Capture](https://github.com/harbassan/spicetify-apps/assets/164070631/fd2032e7-4176-4578-b28c-18a1b6fcf8d0)

**Comment by Garden43** [comment]
You need to put folder "stats" to "CustomApps", not to "marketplace".
But, it still not works :)

**Comment by jaeden642** [comment]
go to releases and download v3.0 i had the same problem and that fixed it for me
