### ISSUE TITLE
[Statistics] App won't load

### ISSUE THREAD

**Issue by RowanBee** [harbassan/spicetify-apps#70]
When I click on the Statistics app all that I see is this:
![image](https://github.com/harbassan/spicetify-apps/assets/47164828/0dc37618-73aa-4082-b9c8-d02891fc186f)

Statistics is on 0.3.1
Spicetify is on 2.36.2

**Comment by pinhead-tf2** [comment]
![image](https://github.com/harbassan/spicetify-apps/assets/42384617/bc3ccd0c-1381-42bc-82d3-3c1b158e01bf)

throws this error on click

**Comment by xylanneal** [comment]
Having the same issue

**Comment by bewiame** [comment]
same with 0.3.1
![image](https://github.com/harbassan/spicetify-apps/assets/5967295/d33a4d47-5d7e-491f-9fb6-230283944498)

**Comment by Bergbok** [comment]
@harbassan You can fix this by updating spcr-navigation bar to V0.0.3

**Comment by zenthedoggo** [comment]
> @harbassan You can fix this by updating spcr-navigation bar to V0.0.3

how do u do that?

**Comment by NotAF0e** [comment]
Yep same issue here

**Comment by marvandorth** [comment]
Same, even after update of module "stats"

**Comment by harbassan** [comment]
fixed in the latest version.

**Comment by CruxH** [comment]
Same behavior with latest version 0.3.2. 
- Spotify for Windows (64 bit) 1.2.34.783.g923721d9
- Spicetify v2.36.2

**Comment by harbassan** [comment]
wait for spicetify to update to the next version, there's a fix in there.
