### ISSUE TITLE
Add License 

### ISSUE THREAD

**Issue by Bergbok** [harbassan/spicetify-apps#71]
Hey,

I used some of your code in my project [here](https://github.com/Bergbok/Spicetify-Creations/blob/main/CustomApps/playlist-tags/src/components/text_input_dialog.tsx) and [here](https://github.com/Bergbok/Spicetify-Creations/blob/main/CustomApps/playlist-tags/src/components/spotify_card.tsx), and only just noticed that it's unlicensed.

`Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.`

Sorry about that, rookie mistake - please don't sue me haha.
If you're not okay with this simply let me know and I'll completely rewrite the components.

Adding a license that allows me to use the code would be very much appreciated.
I recommend: MIT or [WTFPL](http://www.wtfpl.net/)

**Comment by harbassan** [comment]
Hey, im completely fine with you using the code like that, ill definitely add a license aswell at some point.

Btw, your app looks really good! Always cool to see new ideas for plugins. 👍

**Comment by Bergbok** [comment]
❤
