### ISSUE TITLE
Spicetify.ReactComponent.Cards Default undefined

### ISSUE THREAD

**Issue by Bergbok** [harbassan/spicetify-apps#72]
From Spotify V1.2.34> it seems like it got removed. Either that or this is a Spicetify issue.

Which means the following line in [spotify_card.tsx](https://github.com/harbassan/spicetify-apps/blob/main/shared/components/spotify_card.tsx) doesn't work anymore:
`const { Default: Card, CardImage } = Cards;`

This results in Minified React error #130 when rendering SpotifyCard.

V1.2.33:
![image](https://github.com/harbassan/spicetify-apps/assets/66174189/9d4f836e-1fc6-41da-a8bf-313d22ccae62)
V1.2.34:
![image](https://github.com/harbassan/spicetify-apps/assets/66174189/ecf786e2-f0a9-4dd6-a991-44954b7028ef)

Not sure how to go about fixing it.

**Comment by harbassan** [comment]
Spotify just changed the look of their cards, wouldn't be surprised if they either removed it or we need to change the hook. Will do some looking though.

**Comment by harbassan** [comment]
Yep it was the hook that needed changing. Made the fix. https://github.com/spicetify/spicetify-cli/pull/2942
