### ISSUE TITLE
[Library][Enhancement] Folders having default folder icon

### ISSUE THREAD

**Issue by TecEash1** [harbassan/spicetify-apps#74]
<img width="119" alt="image" src="https://github.com/harbassan/spicetify-apps/assets/92249532/f2eb1d60-0a7f-4cd9-a359-13202535c23b">

**Comment by harbassan** [comment]
It's just like that because that's the Spotify card default, but it probably would be a good idea to make it into a folder like the sidebar icons.

**Comment by TecEash1** [comment]
gotcha, also if this helps I believe this is the SVG:

```svg

**Comment by TecEash1** [comment]
https://www.svgviewer.dev/s/BPXruhkO
- *Sorry closing was an accident*

**Comment by harbassan** [comment]
I've just added this alongside the most recent fix.
