### ISSUE TITLE
[Statistics] Playlist Stats infinite loading.

### ISSUE THREAD

**Issue by AegeanExe** [harbassan/spicetify-apps#79]
Playlist Stats gets stuck in the analyzing page if there are any podcasts present. 
Feel free to test it out on my playlist: https://open.spotify.com/playlist/7GK6uqFh9y1S9vuqFpr44k?si=d30192e9a2414a3e

**Comment by Psythra** [comment]
![image](https://github.com/harbassan/spicetify-apps/assets/60825406/aed62027-5f92-46b5-b0b0-8588dcd644c7)
I have this problem

**Comment by MatStar15** [comment]
![image](https://github.com/harbassan/spicetify-apps/assets/39085851/264411c8-6aef-4b11-a465-653ce0b74a72)

same problem here, The Statistics tab asks to reload the page, sending to the Home tab

**Comment by Yashirow** [comment]
same issue
