### ISSUE TITLE
[Library] Folder Images not showing

### ISSUE THREAD

**Issue by HapticFeedbak** [harbassan/spicetify-apps#82]
Not sure if I'm doing something wrong here, but when I type in a file path for an image in the "Set Folder Image" menu, a weird default/null image appears (both on the left sidebar and in the Library app), no matter what path/image I use. For context, here is the path I am using: 

"C:\Users\matts\AppData\Roaming\spicetify\CustomApps\library\folderImages\1.jpg"

And this is what I see in the sidebar/Library app:
![image](https://github.com/harbassan/spicetify-apps/assets/167457237/d4f9a08e-564c-4185-9bd3-f0904622f941)
![image](https://github.com/harbassan/spicetify-apps/assets/167457237/55de12d3-9bfa-44bf-babe-143210109884)

**Comment by harbassan** [comment]
You can't actually use local files for the folder images, its got to be a web img url. If you cant find the pitcures on the internet, id suggest uploading them to a website (anything really) and then using it from there.
