### ISSUE TITLE
Error Screen

### ISSUE THREAD

**Issue by Devin21h** [harbassan/spicetify-apps#85]
UnfortunateIy I get an error screen, I followed the instructions in the README file und ran those comments in powershell

![Screenshot 2024-04-20 204604](https://github.com/harbassan/spicetify-apps/assets/159663309/63d8a6cf-77dc-4586-8a24-59040bbb2e41)

**Comment by OneTapTrap** [comment]
me as well 
![image](https://github.com/harbassan/spicetify-apps/assets/76800482/4c84ef0d-f55d-4a1e-9c92-a121803825c7)

**Comment by harbassan** [comment]
if the icon isn't showing up on the sidebar (which is true for both of you), that means you've installed it wrong. Go back and triple check you did everything correctly.
