### ISSUE TITLE
[Both] Topbar buttons appear enlarged

### ISSUE THREAD

**Issue by TecEash1** [harbassan/spicetify-apps#86]
After updating spicetify it appears that there are a few bugs.

<img width="43" alt="image" src="https://github.com/harbassan/spicetify-apps/assets/92249532/6193f070-b1cb-4870-ad25-1c594608a01b">
<img width="713" alt="image" src="https://github.com/harbassan/spicetify-apps/assets/92249532/24b55089-ac13-43ea-ba99-006c2f9124aa">

**Comment by Maskowh** [comment]
This seems to also break the arrows in the standard playlists list in the bottom left corner.
Those arrows look fine when I remove both stats and library customapps.

![image](https://github.com/harbassan/spicetify-apps/assets/123783610/60300fc5-91a7-4178-856e-c67e3cfc0351)

**Comment by 3131694874** [comment]
![image](https://github.com/harbassan/spicetify-apps/assets/128668650/c7031e83-95a3-4fea-aaa8-a248c3706046)
error

**Comment by harbassan** [comment]
This will be fixed in probably the next spicetify update. Just have to wait a bit for that.

**Comment by pikachub2005** [comment]
It was not fixed 😔
![image](https://github.com/harbassan/spicetify-apps/assets/74213212/adf995b3-7c1e-4519-a694-e5e8bd4273f2)
![Screenshot 2024-04-25 025222](https://github.com/harbassan/spicetify-apps/assets/74213212/c4027b17-d2f0-4873-bfde-b4f43d0f97d8)

**Comment by rxri** [comment]
> This will be fixed in probably the next spicetify update. Just have to wait a bit for that.

@harbassan What am I supposed to fix? Your assigning of `iconSize` to ReactComponent is wrong. You're supposed to pass the number, not the string.

```diff
function AddIcon(): React.ReactElement<SVGElement> {
	return (
		<Spicetify.ReactComponent.IconComponent
			semanticColor="textSubdued"
			dangerouslySetInnerHTML={{
				__html:
					'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M15.25 8a.75.75 0 0 1-.75.75H8.75v5.75a.75.75 0 0 1-1.5 0V8.75H1.5a.75.75 0 0 1 0-1.5h5.75V1.5a.75.75 0 0 1 1.5 0v5.75h5.75a.75.75 0 0 1 .75.75z"></path></svg>',
			}}
-			iconSize="16"
+			iconSize={16}
		/>
	);
}
```
That should be done in all files that are using `IconComponent`

**Comment by rxri** [comment]
> This will be fixed in probably the next spicetify update. Just have to wait a bit for that.

@harbassan What am I supposed to fix? Your assignment of `iconSize` to `IconComponent` is wrong. You're supposed to pass the number, not string. We switched the `IconComponent` component few updates 
ago, however even if it worked before, it wasn't the right way to assign the `iconSize`. We do not pass string to `IconComponent` in wrapper either.

```diff
function AddIcon(): React.ReactElement<SVGElement> {
	return (
		<Spicetify.ReactComponent.IconComponent
			semanticColor="textSubdued"
			dangerouslySetInnerHTML={{
				__html:
					'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M15.25 8a.75.75 0 0 1-.75.75H8.75v5.75a.75.75 0 0 1-1.5 0V8.75H1.5a.75.75 0 0 1 0-1.5h5.75V1.5a.75.75 0 0 1 1.5 0v5.75h5.75a.75.75 0 0 1 .75.75z"></path></svg>',
			}}
-			iconSize="16"
+			iconSize={16}
		/>
	);
}
```
That should be done in all files that are using `IconComponent`

**Comment by harbassan** [comment]
Sweet, i kind of just assumed that it was meant to be that way, ill probably need to change it in a few diff places then because i've probably done this in a lot of different components lol. Thanks tho.
