### ISSUE TITLE
Statistics Page UI.

### ISSUE THREAD

**Issue by Pranav2000-debug** [harbassan/spicetify-apps#90]
**Spicetify version: 2.36.8**
**Installation method: Powershell (pre-built binary)**

**UI to be looked into -** 

1.Settings gear icon is too big.
2. Time period dropdown menu weird behaviour/ inaccessible
![Screenshot 2024-04-28 213723](https://github.com/harbassan/spicetify-apps/assets/72458675/232f0a45-6a2a-4e97-9e82-5e4b669e6ada)

![Screenshot 2024-04-28 213851](https://github.com/harbassan/spicetify-apps/assets/72458675/9dc5e537-1a81-4b75-9385-c525d45dee78)

**Comment by harbassan** [comment]
fixed, update to latest.
