### ISSUE TITLE
[Statistics] Buttons have white outline

### ISSUE THREAD

**Issue by MrPandir** [harbassan/spicetify-apps#92]
<img width="938" alt="Screenshot 2024-05-02 at 12 10 43" src="https://github.com/harbassan/spicetify-apps/assets/137798474/b46d4af2-1928-467b-9386-24470e410747">

spicetify: `2.36.9`
stats: `0.3.3`

**Comment by harbassan** [comment]
I updated the files for the latest release, this should be fixed now.
