### ISSUE TITLE
[Library][Enhancement] Show all playlists inside

### ISSUE THREAD

**Issue by Satanarious** [harbassan/spicetify-apps#95]
In the playlists tab, it would be great to see all the playlists inside a folder and its subfolders, instead of the folders; maybe a switch to toggle this on/off.
<table>
<tr>
<th> Toggle Off
<th> Toggle On
<tr>
<td><img src="https://github.com/harbassan/spicetify-apps/assets/42642682/f068be07-dd00-416d-a5aa-d7e0fcae6b23">
<td><img src="https://github.com/harbassan/spicetify-apps/assets/42642682/202a34c3-a435-479d-a710-b8892953c69d">

</table>

**Comment by harbassan** [comment]
added in latest
