### ISSUE TITLE
[Statistics] Last.fm charts integration broken

### ISSUE THREAD

**Issue by jeetsh4h** [harbassan/spicetify-apps#97]
![image](https://github.com/harbassan/spicetify-apps/assets/113101433/641f7e26-ace6-4a46-9864-1d89eb8d6067)

It was taking way too long to load the last.fm stats and then ended up checking the console. This is the error message that is showing up. 
_There might have been some change in the Last.fm API?_

**Comment by harbassan** [comment]
try out the latest version and let me know if its working

**Comment by jeetsh4h** [comment]
the latest version works perfectly!
