### ISSUE TITLE
Stats On Sidebar Is Not Working

### ISSUE THREAD

**Issue by Claybot27** [harbassan/spicetify-apps#98]
![Capture](https://github.com/harbassan/spicetify-apps/assets/168919275/6b215e63-2cc4-40a0-927a-221dd9ad43ac)

The Stats page & local files (not the library page tho) is support to be in the top sidebar and not the bottom sidebar --it just kind of annoying plz fix it Harbassan. P.S thanks for the code Links

**Comment by harbassan** [comment]
In Spicetify, if you click on your profile icon in the top right, and click on sidebar config, then you can move the sidebar items up and down.
