### ISSUE TITLE
Stats not displaying

### ISSUE THREAD

**Issue by wstenzel** [harbassan/spicetify-apps#99]
Stats page says there is a new update and doesnt show stats. I go to the github, download the latest zip, move it to the correct file and unzip and pull the stats folder into the customapps folder. I run spicetify config custom_apps stats
spicetify apply
I go back to spicetify stats. It still says there is a new update.
![image](https://github.com/harbassan/spicetify-apps/assets/105252070/222038ce-5c13-4f20-b697-f7c9567901c5)

**Comment by harbassan** [comment]
thats because you've done something wrong in the install process. are you installing the zip thats attached to https://github.com/harbassan/spicetify-apps/releases/tag/stats-v0.3.3? If you are, double check everything else in the process is correct, theres no reason it shouldnt work.

**Comment by wstenzel** [comment]
Hi. I just tried again, following all steps correctly, an it still does not show up.

**Comment by harbassan** [comment]
could you show a picture or video of the folder that you've put it into

**Comment by Freaky-Don36** [comment]
Erm what the heck :/ I keep reloading, but nothing happens?? 😖

<img width="1412" alt="Screenshot 2024-05-15 at 12 03 07 AM" src="https://github.com/harbassan/spicetify-apps/assets/169249598/f12833da-2d80-482b-a28d-9964db2f6f39">

**Comment by Freaky-Don36** [comment]
> could you show a picture or video of the folder that you've put it into

I downloaded stats-v0.3.3 and followed the instructions, but nothing changed
<img width="762" alt="Screenshot 2024-05-15 at 11 37 28 AM" src="https://github.com/harbassan/spicetify-apps/assets/169249598/2a05f1e4-9d5a-41ff-9738-16bf638dbae6">

**Comment by harbassan** [comment]
if you're still struggling, run the command `spicetify config-dir` in powershell/terminal and it should bring up the spicetify folder, the app should be in the custom apps folder within this. And remember to run `spicetify apply` after.

**Comment by wstenzel** [comment]
![image](https://github.com/harbassan/spicetify-apps/assets/105252070/12885bcc-dc3e-4f2c-99d8-02a2c8b275d1)

**Comment by harbassan** [comment]
if its the latest release, within the same location as `spicetify config-dir`, its in your config, and you've applied, then i genuinely dont know why it wouldnt work. 

The only solution at that point would be to reinstall spicetify.
